# Generated by Django 4.2.6 on 2023-11-02 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0002_subject_remove_student_teacher_alter_student_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='behavior_grade',
            field=models.CharField(blank=True, choices=[('A', 'Great Job!'), ('B', 'Good'), ('C', 'Somethings to Work On'), ('D', 'We need to setup a meeting')], max_length=2),
        ),
    ]
