# Generated by Django 4.2.6 on 2023-11-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0003_student_behavior_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teacher_report',
            field=models.TextField(blank=True),
        ),
    ]
