# Generated by Django 4.2.6 on 2023-11-22 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0006_alter_teacher_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='pdf_documents/')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='pdf_document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.pdfdocument'),
        ),
    ]
