# Generated by Django 4.2.6 on 2023-11-22 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report_app', '0007_pdfdocument_student_pdf_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pdf_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='report_app.pdfdocument'),
        ),
    ]
