name: Python 3.11.6 CI

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.6'

    # Add your Python-based steps here, such as installing dependencies, running tests, etc.
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: python manage.py test  # Replace with your testing command
